on: pull_request
name: PR check
jobs:
  mvn-java-8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: mvn-java-8
      uses: docker://maven:3.6.3-jdk-8
      with:
        entrypoint: mvn
        args: -U -B -P release verify
